<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
	<PlatformTarget>AnyCPU</PlatformTarget>
    <OutputType>WinExe</OutputType>
    <RootNamespace>DataManagerGUI</RootNamespace>
    <AssemblyName>crdmgui</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="User controls\TreeViewReorder.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="User controls\RegExVarReplace.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="User controls\ParameterManager.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="User controls\DateTimeSlicker.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="User controls\ToolStripNumericUpDown.cs">
      <SubType>Component</SubType>
    </Compile>
    <None Update="dataman.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="user.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	<EmbeddedResource Update="User controls\**\*.resx">
		<LogicalName>$(RootNamespace).%(Filename).resources</LogicalName>
	</EmbeddedResource>
	<EmbeddedResource Update="Forms\**\*.resx">
		<LogicalName>$(RootNamespace).%(Filename).resources</LogicalName>
	</EmbeddedResource>
  </ItemGroup>
  <PropertyGroup>
    <PostBuildEvent>if $(Configuration) == Debug Goto :Exit

xcopy /s /y "$(OutDir)*.exe" "$(MSBuildProjectDirectory)\..\..\..\ComicRack\ComicRack\bin\Release\net48\Data\Scripts\Data Manager\"
xcopy /s /y "$(OutDir)*.exe" "$(MSBuildProjectDirectory)\..\..\..\CRDataManager\"

:Exit</PostBuildEvent>
  </PropertyGroup>
</Project>